package net.iharder.script;

import java.util.List;
import javax.script.*;

/**
 *
 * @author  rob
 */
public class EnginePane extends javax.swing.JPanel {

    /** Creates new form EnginePane */
    public EnginePane() {
        initComponents();
    }
    
    
    public void setFactory( ScriptEngineFactory factory ){
        String engineName = factory.getEngineName();
        String engineVer = factory.getEngineVersion();
        String langName = factory.getLanguageName();
        String langVer = factory.getLanguageVersion();
        List<String> names = factory.getNames();
        List<String> mimes = factory.getMimeTypes();
        List<String> exts = factory.getExtensions();
        
        this.setName( engineName );
        
        System.out.println( "name: " + engineName );
        System.out.println( " ver: " + engineVer );
        System.out.println( "lang: " + langName );
        System.out.println( " ver: " + langVer );
        System.out.println( "names: " + names );
        System.out.println( "mimes: " + mimes );
        System.out.println( "exts : " + exts );
        
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
