package net.iharder.script;

import javax.script.*;
import java.io.*;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author  rob
 */
public class EnginePane extends javax.swing.JPanel {

    private ScriptEngineFactory factory;
    private ScriptEngine engine;

    /** Creates new form EnginePane */
    public EnginePane() {
        initComponents();
    }

    public ScriptEngineFactory getFactory(){
        return this.factory;
    }
    
    public void setFactory( ScriptEngineFactory factory ){
        ScriptEngine engine = factory.getScriptEngine();
        this.factory = factory;
        String engineName = factory.getEngineName();
        String engineVer = factory.getEngineVersion();
        String langName = factory.getLanguageName();
        String langVer = factory.getLanguageVersion();
        List<String> names = factory.getNames();
        List<String> mimes = factory.getMimeTypes();
        List<String> exts = factory.getExtensions();
        boolean invocable = engine instanceof Invocable;

        this.setName( engineName ); // Name the panel (appears in tab also)
        this.engVerLabel.setText( String.format("%s version %s", engineName, engineVer ) );
        this.engVerLabel.setToolTipText("factory.getEngineName()\nfactory.getEngineVersion()");

        this.langVerLabel.setText( String.format("%s version %s", langName, langVer ) );
        this.engVerLabel.setToolTipText("factory.getLanguageName()\nfactory.getLanguageVersion()");

        {   // Names
            StringBuilder sb = new StringBuilder();
            for( String n : names ){
                sb.append( n + ", " );
            }   // end for: each name
            if( sb.length() >= 2 ){
                sb.delete( sb.length()-2, sb.length()-1 );
            }   // end if: not empty
            this.namesLabel.setText( "<html>" + sb + "</html>" );
            this.namesLabel.setToolTipText( "factory.getNames()" );
        }   // end block: Names

        {   // Mime types
            StringBuilder sb = new StringBuilder();
            for( String s : mimes ){
                sb.append( s + ", " );
            }   // end for: each name
            if( sb.length() >= 2 ){
                sb.delete( sb.length()-2, sb.length()-1 );
            }   // end if: not empty
            this.mimesLabel.setText( "<html>" + sb + "</html>" );
            this.mimesLabel.setToolTipText( "factory.getMimeTypes()" );
        }   // end block: Mime types

        {   // Extensions
            StringBuilder sb = new StringBuilder();
            for( String s : exts ){
                sb.append( s + ", " );
            }   // end for: each name
            if( sb.length() >= 2 ){
                sb.delete( sb.length()-2, sb.length()-1 );
            }   // end if: not empty
            this.extsLabel.setText( "<html>" + sb + "</html>" );
            this.extsLabel.setToolTipText( "factory.getExtensions()" );
        }   // end block: Mime types
        
        // Invocable
        if( invocable ){
            this.invLabel.setText( "<html>Yes (Java code can invoke specific functions after the script is loaded.</html>" );
        } else {
            this.invLabel.setText( "<html>No (Java code can only run the whole script, not call specific functions within.</html>" );
        }

        this.jCheckBox1.setToolTipText( "engine.put( \"checkbox\", jCheckBox1 )" );
        this.jProgressBar1.setToolTipText( "engine.put( \"progressbar\", jProgressBar1 )" );
        this.jTextField1.setToolTipText( "engine.put( \"textfield\", jTextField1 )" );
        this.scriptInArea.setText( factory.getOutputStatement("hello, world") );
        this.scriptInArea.requestFocusInWindow();
        
    }


    private void alert( String message ){
        JOptionPane.showMessageDialog(this,message);
    }


    /**
     * Returns the ScriptEngine, possibly reused, and plumbed
     * to intercept output to display in a text area.
     * @param reuse
     * @return
     */
    private synchronized ScriptEngine getEngine( boolean reuse ){

        // If not reusing the engine, clear it
        if( !reuse ){
            this.engine = null;
        }   // end if: not reusing

        // Create script engine if needed
        if( this.engine == null ){
            this.engine = this.factory.getScriptEngine();
            this.engine.put( "checkbox", this.jCheckBox1 );
            this.engine.put( "progressbar", this.jProgressBar1 );
            this.engine.put( "textfield", this.jTextField1 );
        }   // end if: engine == null;

        return this.engine;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        evL = new javax.swing.JLabel();
        lvL = new javax.swing.JLabel();
        langVerLabel = new javax.swing.JLabel();
        engVerLabel = new javax.swing.JLabel();
        nL = new javax.swing.JLabel();
        namesLabel = new javax.swing.JLabel();
        mL = new javax.swing.JLabel();
        mimesLabel = new javax.swing.JLabel();
        eL = new javax.swing.JLabel();
        extsLabel = new javax.swing.JLabel();
        invL = new javax.swing.JLabel();
        invLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        scriptInPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptInArea = new javax.swing.JTextArea();
        runButton = new javax.swing.JButton();
        reuseEngine = new javax.swing.JCheckBox();
        progressBar = new javax.swing.JProgressBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        scriptOutPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scriptOutArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        evL.setText("Engine, version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(evL, gridBagConstraints);

        lvL.setText("Language, version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(lvL, gridBagConstraints);

        langVerLabel.setFont(langVerLabel.getFont().deriveFont(langVerLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        langVerLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(langVerLabel, gridBagConstraints);

        engVerLabel.setFont(engVerLabel.getFont().deriveFont(engVerLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        engVerLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(engVerLabel, gridBagConstraints);

        nL.setText("Names:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(nL, gridBagConstraints);

        namesLabel.setFont(namesLabel.getFont().deriveFont(namesLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        namesLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(namesLabel, gridBagConstraints);

        mL.setText("MIME types:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(mL, gridBagConstraints);

        mimesLabel.setFont(mimesLabel.getFont().deriveFont(mimesLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        mimesLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(mimesLabel, gridBagConstraints);

        eL.setText("Extensions:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(eL, gridBagConstraints);

        extsLabel.setFont(extsLabel.getFont().deriveFont(extsLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        extsLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(extsLabel, gridBagConstraints);

        invL.setText("Invocable:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(invL, gridBagConstraints);

        invLabel.setFont(invLabel.getFont().deriveFont(invLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        invLabel.setText("TBD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 0);
        jPanel1.add(invLabel, gridBagConstraints);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.9);

        scriptInPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Script Source"));

        scriptInArea.setFont(new java.awt.Font("Monospaced", 0, 14));
        scriptInArea.setRows(2);
        scriptInArea.setTabSize(4);
        jScrollPane1.setViewportView(scriptInArea);

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        reuseEngine.setText("Maintain engine state (reduces engine instantiation)");
        reuseEngine.setToolTipText("Maintains variables, function declarations, etc across multiple runs");

        jCheckBox1.setText("I am in a variable called \"checkbox\"");

        jLabel2.setText("I am in a variable called \"progressbar\"");

        jLabel3.setText("I am in a variable called \"textfield\"");

        jTextField1.setColumns(12);

        javax.swing.GroupLayout scriptInPanelLayout = new javax.swing.GroupLayout(scriptInPanel);
        scriptInPanel.setLayout(scriptInPanelLayout);
        scriptInPanelLayout.setHorizontalGroup(
            scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptInPanelLayout.createSequentialGroup()
                .addGroup(scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scriptInPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1))
                    .addGroup(scriptInPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scriptInPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scriptInPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(reuseEngine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(runButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );
        scriptInPanelLayout.setVerticalGroup(
            scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scriptInPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(scriptInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reuseEngine)
                        .addComponent(runButton))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(scriptInPanel);

        scriptOutPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Script Output"));

        scriptOutArea.setEditable(false);
        scriptOutArea.setRows(2);
        jScrollPane2.setViewportView(scriptOutArea);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel1.setText("<html>Unfortunately, the output of some script engines (jython, for example) cannot be intercepted, in which case you will have to look at the console, if you can, to see output.</html>");

        javax.swing.GroupLayout scriptOutPanelLayout = new javax.swing.GroupLayout(scriptOutPanel);
        scriptOutPanel.setLayout(scriptOutPanelLayout);
        scriptOutPanelLayout.setHorizontalGroup(
            scriptOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scriptOutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                .addContainerGap())
        );
        scriptOutPanelLayout.setVerticalGroup(
            scriptOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptOutPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(scriptOutPanel);

        jPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        this.runButton.setEnabled(false);
        this.progressBar.setIndeterminate(true);
        final String script = this.scriptInArea.getText();
        final boolean reuse = this.reuseEngine.isSelected();
        this.scriptOutArea.setText("");

        SwingWorker<Object,String> sw = new SwingWorker<Object,String>(){
            @Override
            protected Object doInBackground() throws Exception {
                ScriptEngine e = getEngine( reuse );
                e.getContext().setWriter( new PrintWriter( new Writer() {
                    StringBuilder sb = new StringBuilder();
                    @Override
                    public void write(char[] cbuf, int off, int len) throws IOException {
                        sb.append(cbuf, off, len);
                    }   // end write

                    @Override
                    public void flush() throws IOException {
                        final String s = sb.toString();
                        publish(s);
                    }   // end flush

                    @Override
                    public void close() throws IOException {
                        final String s = sb.toString();
                        publish(s);
                    }   // end close
                }));
                
                return e.eval(script);
            }   // end doInBackground
            
            @Override
            protected void process( List<String> chunks ){
                StringBuilder sb = new StringBuilder();
                for( String s : chunks ){
                    sb.append(s);
                }   // end for: each string
                scriptOutArea.setText( scriptOutArea.getText() + sb );
            }

            @Override
            protected void done(){
                Object result = null;
                try {
                    result = get();
                } catch (InterruptedException ex) {
                    Logger.getLogger(EnginePane.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    alert(ex.getMessage());
                    Logger.getLogger(EnginePane.class.getName()).log(Level.SEVERE, null, ex);
                }
                runButton.setEnabled(true);
                progressBar.setIndeterminate(false);
            }   // end done
        };
        sw.execute();
    }//GEN-LAST:event_runButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eL;
    private javax.swing.JLabel engVerLabel;
    private javax.swing.JLabel evL;
    private javax.swing.JLabel extsLabel;
    private javax.swing.JLabel invL;
    private javax.swing.JLabel invLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel langVerLabel;
    private javax.swing.JLabel lvL;
    private javax.swing.JLabel mL;
    private javax.swing.JLabel mimesLabel;
    private javax.swing.JLabel nL;
    private javax.swing.JLabel namesLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JCheckBox reuseEngine;
    private javax.swing.JButton runButton;
    private javax.swing.JTextArea scriptInArea;
    private javax.swing.JPanel scriptInPanel;
    private javax.swing.JTextArea scriptOutArea;
    private javax.swing.JPanel scriptOutPanel;
    // End of variables declaration//GEN-END:variables

}
