/*
 * LoadFromJarsPanel.java
 *
 * Created on October 27, 2008, 2:04 PM
 */

package net.iharder.script;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.ListModel;

/**
 *
 * @author  Student
 */
public class LoadFromJarsPanel extends javax.swing.JPanel {
    
    private Preferences prefs;

    /** Creates new form LoadFromJarsPanel */
    public LoadFromJarsPanel() {
        initComponents();
        new FileDrop( this.jarList, new FileDrop.Listener() {
            @Override
            public void filesDropped(File[] files) {
                for( File f : files ){
                    ((DefaultListModel)jarList.getModel()).addElement(f);
                }
            }
        });
    }
    
    public void setPreferences( Preferences prefs ){
        this.prefs = prefs;
    }
    
    public List<File> getFiles(){
        ListModel model = this.jarList.getModel();
        int size = model.getSize();
        List<File> files = new ArrayList<File>( size );
        for( int i = 0; i < size; i++ ){
            files.add( (File)model.getElementAt(i) );
        }
        return files;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jarList = new javax.swing.JList();
        browseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jarList.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jarList);

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("<html><p>You can add scripting language dynamically from JAR files. Select all the relevant JAR files for the language you are adding. It is essential that you have all the JAR files loaded at once. Typically you'll have at least two JAR files, one for the language itself and one probably called yourlanguage-engine.jar and probably from scripting.dev.java.net.</p><br /><p>Browse to the JAR files you want to add, or drag and drop them into this window. When you're done. Click OK.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
String prev = prefs.get("previous_jar_directory", "");
        JFileChooser jfc = new JFileChooser(prev);
        jfc.setMultiSelectionEnabled(true);
        int result = jfc.showOpenDialog(this);
        if( result == JFileChooser.APPROVE_OPTION ){
            File[] files = jfc.getSelectedFiles();
            for( File f : files ){
                prefs.put("previous_jar_directory", f.getParentFile() == null ? "" : f.getParentFile().toString() );
                System.out.println(f);
                ((DefaultListModel)this.jarList.getModel()).addElement(f);
            }   // end for: each file
        }
}//GEN-LAST:event_browseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jarList;
    // End of variables declaration//GEN-END:variables

}
