/*
 * Main.java
 *
 * Created on October 14, 2008, 8:19 PM
 */

package net.iharder.script;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.script.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author  rob
 */
public class Main extends javax.swing.JFrame {

    private Preferences prefs = Prefs.get(this);

    /** Creates new form Main */
    public Main() {
        initComponents();
        myInitComponents();
    }
    
    private void myInitComponents(){
        
        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for( ScriptEngineFactory f : factories ){
            addFactory( f );
        }
    }
    
    
    /**
     * Adds a ScriptEngineFactory to the layout.
     * Call on event thread.
     * @param factory
     */
    private void addFactory( ScriptEngineFactory factory ){
        int prevCount = this.enginesTabbedPane.getTabCount();
        for( int i = 0; i < prevCount; i++ ){
            EnginePane ep = (EnginePane)this.enginesTabbedPane.getComponent(i);
            ScriptEngineFactory f = ep.getFactory();
            if( ep != null && factory.getEngineName().equals(f.getEngineName()) && factory.getEngineVersion().equals( f.getEngineVersion() ) ){
                System.out.println("Already have this loaded: " + factory.getEngineName() );
                return;
            }
        }
        EnginePane pane = new EnginePane();
        pane.setFactory( factory );
        this.enginesTabbedPane.add( pane );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        enginesTabbedPane = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Javax Scripting Explorer");

        jLabel1.setText("<html>Welcome to the Javax Script Explorer. You have the following Script Engines in your classpath:</html>");

        jButton1.setText("Find JARs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jButton4.setText("Load JARs");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enginesTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(enginesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String prev = prefs.get("previous_jar_directory", "");
        JFileChooser jfc = new JFileChooser(prev);
        jfc.setMultiSelectionEnabled(true);
        int result = jfc.showOpenDialog(this);
        if( result == jfc.APPROVE_OPTION ){
            File[] files = jfc.getSelectedFiles();
            for( File f : files ){
                prefs.put("previous_jar_directory", f.getParentFile() == null ? "" : f.getParentFile().toString() );
                System.out.println(f);
                ((DefaultListModel)this.jList1.getModel()).addElement(f);
            }   // end for: each file
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultListModel dlm = (DefaultListModel)this.jList1.getModel();
        URL[] urls = new URL[ dlm.getSize() ];
        for( int i = 0; i < urls.length; i++ ){
            try {
                File f = (File) dlm.get(i);
                String urlPath;
                urlPath = "jar:file://" + f.getCanonicalPath() + "!/";
                urls[i] = new URL(urlPath);
            } catch (MalformedURLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        System.out.println("URLs to load:");
        for( int i = 0; i < urls.length; i++ ){
            System.out.println("  " + urls[i] );
        }
        URLClassLoader loader = URLClassLoader.newInstance( urls, this.getClass().getClassLoader() );
        ScriptEngineManager manager = new ScriptEngineManager(loader);
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for( ScriptEngineFactory f : factories ){
            addFactory( f );
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane enginesTabbedPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
