/*
 * Example.java
 *
 * Created on March 2, 2008, 6:38 PM
 */

package net.iharder.gauge;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.print.attribute.Attribute;
import javax.print.attribute.AttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;

/**
 *
 * @author  robert.harder
 */
public class Example extends javax.swing.JFrame implements Printable {
    
    float altitude = 7200;
    float roll = 0;
    float pitch = 0;
    float yaw = 0;
    int rpm = 2000;
    float voltage = 12;
    float airspeed = 20;
    
    /** Creates new form Example */
    public Example() {
        initComponents();
        javax.swing.Timer timer = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                //altitude += -5 + Math.random()*10;
                altitude += Math.random()*2;
                roll += -2 + Math.random()*4;
                pitch += -2 + Math.random()*4;
                yaw += -2 + Math.random()*4;
                rpm += -50 + Math.random()*120;
                voltage += -.05 + Math.random()*.08;
                airspeed += -.1 + Math.random()*.2;
                
                altimeterGauge1.setAltitude(altitude);
                altimeterPhotorealisticGauge1.setAltitude(altitude);
                verticalSpeedGauge1.setAltitude(altitude);
                rollGauge1.setRoll(roll);
                pitchGauge1.setPitch(pitch);
                yawGauge1.setYaw(yaw);
                tachometerGauge1.setRPM(rpm);
                voltageGauge1.setVoltage(voltage);
                airspeedGauge1.setAirspeed(airspeed);
            }
        });
        timer.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airspeedGauge1 = new net.iharder.gauge.AirspeedGauge();
        altimeterGauge1 = new net.iharder.gauge.AltimeterGauge();
        altimeterPhotorealisticGauge1 = new net.iharder.gauge.AltimeterPhotorealisticGauge();
        pitchGauge1 = new net.iharder.gauge.PitchGauge();
        rollGauge1 = new net.iharder.gauge.RollGauge();
        yawGauge1 = new net.iharder.gauge.YawGauge();
        verticalSpeedGauge1 = new net.iharder.gauge.VerticalSpeedGauge();
        tachometerGauge1 = new net.iharder.gauge.TachometerGauge();
        voltageGauge1 = new net.iharder.gauge.VoltageGauge();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Example Gauges");
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout airspeedGauge1Layout = new javax.swing.GroupLayout(airspeedGauge1);
        airspeedGauge1.setLayout(airspeedGauge1Layout);
        airspeedGauge1Layout.setHorizontalGroup(
            airspeedGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        airspeedGauge1Layout.setVerticalGroup(
            airspeedGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(airspeedGauge1);

        altimeterGauge1.setName("ALT"); // NOI18N

        javax.swing.GroupLayout altimeterGauge1Layout = new javax.swing.GroupLayout(altimeterGauge1);
        altimeterGauge1.setLayout(altimeterGauge1Layout);
        altimeterGauge1Layout.setHorizontalGroup(
            altimeterGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        altimeterGauge1Layout.setVerticalGroup(
            altimeterGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(altimeterGauge1);

        javax.swing.GroupLayout altimeterPhotorealisticGauge1Layout = new javax.swing.GroupLayout(altimeterPhotorealisticGauge1);
        altimeterPhotorealisticGauge1.setLayout(altimeterPhotorealisticGauge1Layout);
        altimeterPhotorealisticGauge1Layout.setHorizontalGroup(
            altimeterPhotorealisticGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        altimeterPhotorealisticGauge1Layout.setVerticalGroup(
            altimeterPhotorealisticGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(altimeterPhotorealisticGauge1);

        pitchGauge1.setName("PITCH"); // NOI18N

        javax.swing.GroupLayout pitchGauge1Layout = new javax.swing.GroupLayout(pitchGauge1);
        pitchGauge1.setLayout(pitchGauge1Layout);
        pitchGauge1Layout.setHorizontalGroup(
            pitchGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        pitchGauge1Layout.setVerticalGroup(
            pitchGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(pitchGauge1);

        rollGauge1.setName("ROLL"); // NOI18N

        javax.swing.GroupLayout rollGauge1Layout = new javax.swing.GroupLayout(rollGauge1);
        rollGauge1.setLayout(rollGauge1Layout);
        rollGauge1Layout.setHorizontalGroup(
            rollGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        rollGauge1Layout.setVerticalGroup(
            rollGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(rollGauge1);

        javax.swing.GroupLayout yawGauge1Layout = new javax.swing.GroupLayout(yawGauge1);
        yawGauge1.setLayout(yawGauge1Layout);
        yawGauge1Layout.setHorizontalGroup(
            yawGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        yawGauge1Layout.setVerticalGroup(
            yawGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(yawGauge1);

        verticalSpeedGauge1.setMaxVerticalSpeedMarking(20);

        javax.swing.GroupLayout verticalSpeedGauge1Layout = new javax.swing.GroupLayout(verticalSpeedGauge1);
        verticalSpeedGauge1.setLayout(verticalSpeedGauge1Layout);
        verticalSpeedGauge1Layout.setHorizontalGroup(
            verticalSpeedGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        verticalSpeedGauge1Layout.setVerticalGroup(
            verticalSpeedGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(verticalSpeedGauge1);

        tachometerGauge1.setName("RPM"); // NOI18N
        tachometerGauge1.setYellowline(6200);

        javax.swing.GroupLayout tachometerGauge1Layout = new javax.swing.GroupLayout(tachometerGauge1);
        tachometerGauge1.setLayout(tachometerGauge1Layout);
        tachometerGauge1Layout.setHorizontalGroup(
            tachometerGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        tachometerGauge1Layout.setVerticalGroup(
            tachometerGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(tachometerGauge1);

        javax.swing.GroupLayout voltageGauge1Layout = new javax.swing.GroupLayout(voltageGauge1);
        voltageGauge1.setLayout(voltageGauge1Layout);
        voltageGauge1Layout.setHorizontalGroup(
            voltageGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        voltageGauge1Layout.setVerticalGroup(
            voltageGauge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        getContentPane().add(voltageGauge1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Example().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.iharder.gauge.AirspeedGauge airspeedGauge1;
    private net.iharder.gauge.AltimeterGauge altimeterGauge1;
    private net.iharder.gauge.AltimeterPhotorealisticGauge altimeterPhotorealisticGauge1;
    private net.iharder.gauge.PitchGauge pitchGauge1;
    private net.iharder.gauge.RollGauge rollGauge1;
    private net.iharder.gauge.TachometerGauge tachometerGauge1;
    private net.iharder.gauge.VerticalSpeedGauge verticalSpeedGauge1;
    private net.iharder.gauge.VoltageGauge voltageGauge1;
    private net.iharder.gauge.YawGauge yawGauge1;
    // End of variables declaration//GEN-END:variables

    public int print(Graphics g, PageFormat pf, int page) throws PrinterException {
        if (page > 0) { /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }

        /* User (0,0) is typically outside the imageable area, so we must
         * translate by the X and Y values in the PageFormat to avoid clipping
         */
        Graphics2D g2d = (Graphics2D)g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());

        /* Now we perform our rendering */
        //g.drawString("Hello world!", 100, 100);
        paint(g);

        /* tell the caller that this page is part of the printed document */
        return PAGE_EXISTS;
    }
    
}
